### ISSUE TITLE
Scenario Enhancements

### ISSUE THREAD

**Issue by raygig** [Firestitch/Framework#5]
Tags are now available
![image](https://cloud.githubusercontent.com/assets/1569098/11320349/f9a3d7c8-9063-11e5-8b3c-41888dea1baf.png)

Default headers are also available when creating new evenets
![image](https://cloud.githubusercontent.com/assets/1569098/11320343/cda51af6-9063-11e5-8584-61266a916ab8.png)

**Comment by wendygull** [comment]
Added to the Scenarios Management doc in Google Drive.
